### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zocom-david-lundholm** [KaptenAlex/nackademin-todo-app#3]
Enhetstesterna ser bra ut förutom en detalj, tänk på att varje test ska vara self contained och självförklarande. Följ Arrange -> Act -> Assert mönstret.

Exempel när du testar din `count` så ser testet ut såhär:
const todos = countTodos()
expect(todos.length).to.be(1)

Det här testet är beroende av någon state som inte är synligt i testet, dvs. den saknar en arrange.

Se över dina enhetstester innan du går vidare med integrationstester.

**Comment by KaptenAlex** [comment]
Förstår vad du menar och ska fixa det, men räknas det inte som en arrange om jag gör ett object i beforeEach().
Jag tycker det känns lite som man duplicerar koden om jag har t.ex. en createTodoItem() anrop i just det testet då jag redan har gjort ett i beforeEach()
